# Generated by Django 5.0.3 on 2024-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.IntegerField()),
                ('meu_id', models.PositiveIntegerField(default=9, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
