# Generated by Django 5.0.3 on 2024-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='meu_id',
            field=models.PositiveIntegerField(default=40, unique=True),
        ),
    ]
