# Generated by Django 5.0.3 on 2024-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_alter_cadastro_meu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='meu_id',
            field=models.PositiveIntegerField(default=94, unique=True),
        ),
    ]
